name: Run Unit Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  ShellCheck:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout FNALLPC/lpc-scripts
      uses: actions/checkout@v2
    - name: Install Bats dependency
      # From https://bats-core.readthedocs.io/en/stable/installation.html#installing-bats-from-source
      run: |
        git submodule add https://github.com/bats-core/bats-core.git test/bats
        git submodule add https://github.com/bats-core/bats-support.git test/test_helper/bats-support
        git submodule add https://github.com/bats-core/bats-assert.git test/test_helper/bats-assert
    - name: Run Bats tests
      # https://bats-core.readthedocs.io/en/stable/
      run: |
        ./test/bats/bin/bats test/test.bats
